/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsFileNameRouteImport } from './routes/payments.$fileName'
import { Route as BreakdownFileNameRouteImport } from './routes/breakdown.$fileName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFileNameRoute = PaymentsFileNameRouteImport.update({
  id: '/payments/$fileName',
  path: '/payments/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakdownFileNameRoute = BreakdownFileNameRouteImport.update({
  id: '/breakdown/$fileName',
  path: '/breakdown/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breakdown/$fileName': typeof BreakdownFileNameRoute
  '/payments/$fileName': typeof PaymentsFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breakdown/$fileName': typeof BreakdownFileNameRoute
  '/payments/$fileName': typeof PaymentsFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breakdown/$fileName': typeof BreakdownFileNameRoute
  '/payments/$fileName': typeof PaymentsFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/breakdown/$fileName' | '/payments/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/breakdown/$fileName' | '/payments/$fileName'
  id: '__root__' | '/' | '/breakdown/$fileName' | '/payments/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreakdownFileNameRoute: typeof BreakdownFileNameRoute
  PaymentsFileNameRoute: typeof PaymentsFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$fileName': {
      id: '/payments/$fileName'
      path: '/payments/$fileName'
      fullPath: '/payments/$fileName'
      preLoaderRoute: typeof PaymentsFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakdown/$fileName': {
      id: '/breakdown/$fileName'
      path: '/breakdown/$fileName'
      fullPath: '/breakdown/$fileName'
      preLoaderRoute: typeof BreakdownFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreakdownFileNameRoute: BreakdownFileNameRoute,
  PaymentsFileNameRoute: PaymentsFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
